# .github/workflows/terraform-checks.yaml
name: Terraform checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  pull-request-terraform-checks:
    name: PR Terraform checks
    uses: canonical/workflows-team/.github/workflows/terraform.yaml@main
    with:
      module-directory: ./modules/charmed-nifi
      just-targets: '["test", "test-git-integrator", "test-traefik"]'
      timeout-minutes: 120
